//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysClin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public Cita()
        {
            this.Cita1 = new HashSet<Cita>();
        }
    
        public int ID_Cita { get; set; }
        public int ID_Paciente { get; set; }
        public int ID_Profesional { get; set; }
        public int ID_Servicio { get; set; }
        public int ID_Estado_Cita { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
        public int? ID_Cita_Original { get; set; }
    
        public virtual ICollection<Cita> Cita1 { get; set; }
        public virtual Cita Cita2 { get; set; }
        public virtual EstadoCita EstadoCita { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
