//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysClin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerfilProfesional
    {
        public int ID_Perfil_Profesional { get; set; }
        public int ID_Usuario { get; set; }
        public int ID_Especialidad { get; set; }
        public string Lugar_Atencion { get; set; }
        public int? Tiempo_Anticipacion { get; set; }
        public string Unidad_Anticipacion { get; set; }
    
        public virtual Especialidad Especialidad { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
