//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysClin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        public Servicio()
        {
            this.Cita = new HashSet<Cita>();
        }
    
        public int ID_Servicio { get; set; }
        public int ID_Usuario { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public decimal Precio { get; set; }
    
        public virtual ICollection<Cita> Cita { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
