//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysClin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoIdentificacion
    {
        public TipoIdentificacion()
        {
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int ID_Tipo_Identificacion { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
