//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysClin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Especialidad
    {
        public Especialidad()
        {
            this.PerfilProfesional = new HashSet<PerfilProfesional>();
        }
    
        public int ID_Especialidad { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<PerfilProfesional> PerfilProfesional { get; set; }
    }
}
