//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysClin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorarioAtencion
    {
        public int ID_Horario { get; set; }
        public int ID_Usuario { get; set; }
        public string Dia_Semana { get; set; }
        public System.TimeSpan Hora_Inicio { get; set; }
        public System.TimeSpan Hora_Fin { get; set; }
        public int Duracion_Minutos { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
