//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysClin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SysClinEntities : DbContext, ISysClinContext
    {
        public SysClinEntities()
            : base("name=SysClinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BloqueoHorario> BloqueoHorario { get; set; }
        public DbSet<Cita> Cita { get; set; }
        public DbSet<Especialidad> Especialidad { get; set; }
        public DbSet<EstadoCita> EstadoCita { get; set; }
        public DbSet<HorarioAtencion> HorarioAtencion { get; set; }
        public DbSet<PerfilProfesional> PerfilProfesional { get; set; }
        public DbSet<RecuperacionContrasena> RecuperacionContrasena { get; set; }
        public DbSet<Servicio> Servicio { get; set; }
        public DbSet<TipoIdentificacion> TipoIdentificacion { get; set; }
        public DbSet<TipoUsuario> TipoUsuario { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
    }
}
