//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysClin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecuperacionContrasena
    {
        public int ID_Recuperacion_Contrasena { get; set; }
        public int ID_Usuario { get; set; }
        public string Codigo { get; set; }
        public System.DateTime Fecha_Solicitud { get; set; }
        public System.DateTime Fecha_Expiracion { get; set; }
        public bool Usado { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
