//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysClin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.BloqueoHorario = new HashSet<BloqueoHorario>();
            this.Cita = new HashSet<Cita>();
            this.Cita1 = new HashSet<Cita>();
            this.HorarioAtencion = new HashSet<HorarioAtencion>();
            this.PerfilProfesional = new HashSet<PerfilProfesional>();
            this.RecuperacionContrasena = new HashSet<RecuperacionContrasena>();
            this.Servicio = new HashSet<Servicio>();
        }
    
        public int ID_Usuario { get; set; }
        public int ID_Tipo_Usuario { get; set; }
        public int ID_Tipo_Identificacion { get; set; }
        public string Numero_Identificacion { get; set; }
        public string Nombre { get; set; }
        public string Primer_Apellido { get; set; }
        public string Segundo_Apellido { get; set; }
        public string Correo_Electronico { get; set; }
        public string Contrasena { get; set; }
        public string Telefono { get; set; }
        public System.DateTime Fecha_Nacimiento { get; set; }
    
        public virtual ICollection<BloqueoHorario> BloqueoHorario { get; set; }
        public virtual ICollection<Cita> Cita { get; set; }
        public virtual ICollection<Cita> Cita1 { get; set; }
        public virtual ICollection<HorarioAtencion> HorarioAtencion { get; set; }
        public virtual ICollection<PerfilProfesional> PerfilProfesional { get; set; }
        public virtual ICollection<RecuperacionContrasena> RecuperacionContrasena { get; set; }
        public virtual ICollection<Servicio> Servicio { get; set; }
        public virtual TipoIdentificacion TipoIdentificacion { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
    }
}
